services:
  - type: web
    name: whatsapp-bulk-sender
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: ACCESS_TOKEN
        value: your_access_token_here
      - key: PHONE_NUMBER_ID
        value: your_phone_number_id_here
      - key: API_VERSION
        value: v19.0
